# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        echo "Installing OWASP Dependency Check"
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
        unzip dependency-check-6.1.6-release.zip
    displayName: 'Install OWASP Dependency Check'

- task: Bash@3 
  inputs:
    targetType: 'inline'
    script: |
          ./dependency-check/bin/dependency-check.sh \
          --project "MyProject" \
          --scan "$(System.DefaultWorkingDirectory)" \
          --format "HTML" \
          --out "$(System.DefaultWorkingDirectory)/odc-reports"


  displayName: 'Run OWASP Dependency-Check'
- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s/webapp/target/'
    Contents: 'webapp.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Warfile'
    publishLocation: 'Container'

