# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s/webapp/target/'
    Contents: 'webapp.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Warfile'
    publishLocation: 'Container'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        echo "Installing Trivy."
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    displayName: 'Install Trivy'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        echo Running Trivy Scan...
        trivy image --format template --template "@trivy-reports.tpl" --output "$(Build.ArtifactStagingDirectory)/trivy-report.html" karthiktum/spring:latest
    displayName: 'Run Trivy Scan'
