# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s/webapp/target/'
    Contents: 'webapp.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'war file'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'docker2'
    command: 'login'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- script: |
       sudo apt-get update
       sudo apt-get -y install curl jq
- script: |
          mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=azuredevsecops09-2025 -Dsonar.projectKey=azuredevsecops09-2025_azuredevsecops09-2025 -Dsonar.token=385d1ca41605e46a237e197c7a9c5d66104f70b7 
- task: Docker@2
  inputs:
    containerRegistry: 'docker2'
    repository: 'bostondataengineer/dso09app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Trivy."
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.64.0
  displayName: 'Install Trivy' 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo Running Trivy Scan...
      trivy image bostondataengineer/dso09app
  displayName: 'Run Trivy Scan'

